const NODE_CHANGE = 'routing/NODE_CHANGE'
const ROUTE_CHANGE = 'routing/ROUTE_CHANGE'
const NAVIGATE = 'routing/NAVIGATE'
const ROUTER_STARTED = 'routing/ROUTER_STARTED'

export default {
  NODE_CHANGE,
  ROUTE_CHANGE,
  NAVIGATE,
  ROUTER_STARTED
}
