const READ_COMMIT = 'record/READ_COMMIT'
const RECORDS_CHANGE = 'record/RECORDS_CHANGE'
const FETCH_RECORDS = 'record/FETCH_RECORDS'
const UPDATE_RECORD = 'record/UPDATE_RECORD'
const ADD_BOOK_TO_RECORD = 'record/ADD_BOOK_TO_RECORD'
const ADD_BOOK_TO_RECORD_PENDING = 'record/ADD_BOOK_TO_RECORD_PENDING'
const ADD_BOOK_TO_RECORD_DONE = 'record/ADD_BOOK_TO_RECORD_DONE'

export default {
  READ_COMMIT,
  RECORDS_CHANGE,
  FETCH_RECORDS,
  UPDATE_RECORD,
  ADD_BOOK_TO_RECORD,
  ADD_BOOK_TO_RECORD_DONE,
  ADD_BOOK_TO_RECORD_PENDING
}
