const READ_COMMIT = 'record/READ_COMMIT'
const RECORDS_CHANGE = 'record/RECORDS_CHANGE'
const FETCH_RECORDS = 'record/FETCH_RECORDS'

export default {
  READ_COMMIT,
  RECORDS_CHANGE,
  FETCH_RECORDS
}
