const AUTH_STATE_CHANGE = 'session/AUTH_STATE_CHANGE'
const REGISTER = 'session/REGISTER'
const REGISTER_ERROR = 'session/REGISTER_ERROR'
const CLEAR_REGISTER_ERROR = 'session/CLEAR_REGISTER_ERROR'
const SIGN_OUT = 'session/SIGN_OUT'
const SIGN_IN = 'session/SIGN_IN'
const SIGN_IN_ERROR = 'session/SIGN_IN_ERROR'
const CLEAR_SIGN_IN_ERROR = 'session/CLEAR_SIGN_IN_ERROR'

export default {
  AUTH_STATE_CHANGE,
  REGISTER,
  REGISTER_ERROR,
  CLEAR_REGISTER_ERROR,
  SIGN_OUT,
  SIGN_IN,
  SIGN_IN_ERROR,
  CLEAR_SIGN_IN_ERROR
}
